### ISSUE TITLE
Color by PanelType

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/sam-viewer#4]
Set default colour based on PanelType

**PanelType	| Color Hex**
InteriorWall	#008000
ExteriorWall	#FFB400
Roof	#800000
InteriorFloor	#80FFFF
ExposedFloor	#40B4FF
Shade	#FFCE9D
UndergroundWall	#A55200
UndergroundSlab	#804000
Ceiling	#FF8080
Air	#FFFF00
UndergroundCeiling	#408080
RaisedFloor	#4B417D
SlabOnGrade	#804000
FreestandingColumn	#808080
EmbeddedColumn	#80806E
![image](https://user-images.githubusercontent.com/14005893/31637567-2ab03456-b2c7-11e7-8293-29285f8341ea.png)

**Comment by theo-armour** [comment]
@ZiolkowskiJakub @michaldengusiak 

The two of you are not in agreement regarding the names of panel types

Which is it: WallExternal or ExteriorWall??  And under what authority or guidance?

**Comment by michaldengusiak** [comment]
@theo-armour 
aa sorry you are seems I copied from other repo you right our PanelType name is a bit different here is correct PanelTypes

https://github.com/HoareLea/SAM/blob/master/SAM/SAM.Analytical/Enums/PanelType.cs

```
    public enum PanelType
    {
        Undefined, #808080
        Ceiling, #FF8080
        CurtainWall, #dda0dd Plum
        Floor,#ff1493 DeepPink
        FloorExposed, #40B4FF
        FloorInternal, #80FFFF
        FloorRaised, #4B417D
        Roof, #800000
        Shade, #FFCE9D
        SlabOnGrade, #804000
        SolarPanel, #e9967a
        UndergroundCeiling, #408080
        UndergroundSlab, #804000
        UndergroundWall, #A55200
        Wall, #ff8c00
        WallExternal, #FFB400
        WallInternal, #008000
    }
```

https://github.com/HoareLea/SAM/blob/master/SAM/SAM.Analytical/Enums/ApertureType.cs
```
    public enum ApertureType
    {
        Undefined,
        Window, #0000ff Blue
        Door #cd853f Peru
    }
```

**Comment by theo-armour** [comment]
@michaldengusiak 

several of the types have incorrect color designations. please check and fix hex colors

**Comment by michaldengusiak** [comment]
@theo-armour correct, I was using System colours from ARGB now updated to Hex value

**Comment by theo-armour** [comment]
@michaldengusiak 

If current version looks OK, can you close this issue?

**Comment by michaldengusiak** [comment]
perfect works fine!
